apiVersion: batch/v1
kind: Job
metadata:
  name: parsec-splash2x-fft
  labels:
    name: pasec-splash2x-fft
spec:
  template:
    spec:
      containers:
      - image: anakli/parsec:splash2x-fft-native-reduced
        name: parsec-splash2x-fft
        resources: 
          limits: 
            cpu: "2.0"
        imagePullPolicy : Always
        command: ["/bin/sh"]
        args: ["-c", "taskset -c 6-7 ./bin/parsecmgmt -a run -p splash2x.fft -i native -n 2"]
      restartPolicy: Never
      nodeSelector:
        cca-project-nodetype: "node-c-8core"
