apiVersion: batch/v1
kind: Job
metadata:
  name: parsec-ferret
  labels:
    name: pasec-ferret
spec:
  template:
    spec:
      containers:
      - image: anakli/parsec:ferret-native-reduced
        name: parsecferret
        resources: 
          limits: 
            cpu: "4"
        imagePullPolicy: Always
        command : ["/bin/sh"]
        args: ["-c", "taskset -c 0-3 ./bin/parsecmgmt -a run -p ferret -i native -n 4"]
      restartPolicy: Never
      nodeSelector:
        cca-project-nodetype: "node-b-4core"
