apiVersion: batch/v1
kind: Job
metadata:
  name: parsec-freqmine
  labels:
    name: pasec-freqmine
spec:
  template:
    spec:
      containers:
      - image: anakli/parsec:simlarge
        name: parsecfreqmine
        resources:
          limits: 
            cpu: "6.0"
        imagePullPolicy: Always
        command: ["/bin/sh"]
        args: ["-c", "taskset -c 0-5 ./bin/parsecmgmt -a run -p freqmine -i native -n 6"]
      restartPolicy: Never
      nodeSelector:
        cca-project-nodetype: "node-c-8core"
