apiVersion: batch/v1
kind: Job
metadata:
  name: parsec-canneal
  labels:
    name: pasec-canneal
spec:
  template:
    spec:
      containers:
      - image: anakli/parsec:simlarge
        name: parseccanneal
	  resources: 
          limits: 
            cpu: "3"
        imagePullPolicy: Always
        command: ["/bin/sh"]
        args: ["-c", "taskset -c 0-2 ./bin/parsecmgmt -a run -p canneal -i simlarge -n 3"]
      restartPolicy: Never
      nodeSelector:
        cca-project-nodetype: "node-c-8core"
